export const ukrainianCities = [
  "Kyiv",
  "Kharkiv",
  "Odesa",
  "Dnipro",
  "Donetsk",
  "Zaporizhzhia",
  "Lviv",
  "Kryvyi Rih",
  "Mykolaiv",
  "Mariupol",
  "Luhansk",
  "Vinnytsia",
  "Kherson",
  "Poltava",
  "Chernihiv",
  "Cherkasy",
  "Zhytomyr",
  "Sumy",
  "Khmelnytskyi",
  "Chernivtsi",
  "Rivne",
  "Ivano-Frankivsk",
  "Ternopil",
  "Kropyvnytskyi",
  "Lutsk",
  "Uzhhorod",
  "Melitopol",
  "Kamianets-Podilskyi",
  "Kerch",
  "Sevastopol",
  "Simferopol",
  "Kramatorsk",
  "Sloviansk",
  "Bila Tserkva",
  "Kremenchuk",
  "Berdiansk",
  "Drohobych",
  "Nizhyn",
  "Pavlohrad",
  "Kovel",
  "Oleksandriia",
  "Yevpatoriia",
  "Konotop",
  "Nikopol",
  "Uman",
  "Izmail",
  "Brovary",
  "Mukachevo",
  "Berdychiv",
  "Lysychansk",
  "Yalta",
  "Alchevsk",
  "Feodosiia",
  "Stryi",
  "Kolomyia",
  "Kalush",
  "Korosten",
  "Novohrad-Volynskyi",
  "Smila",
  "Bucha",
  "Irpin",
  "Kamianske",
  "Makiivka",
  "Horlivka",
  "Yenakiieve",
  "Stakhanov",
  "Krasnodon",
  "Khrustalnyi",
  "Antratsyt",
  "Shostka",
  "Pryluky",
  "Kostiantynivka",
  "Izium",
  "Bakhmut",
  "Marhanets",
  "Zhovti Vody",
  "Toretsk",
  "Romny",
];

export const CARRIER = "Ukrzaliznytsia";

export const initialValues = {
  departure: "",
  destination: "",
  departureTime: "",
  arrivalTime: "",
  number: "",
  carrier: CARRIER,
};
